routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware(['auth:sanctum', 'verified'])->group(function () {

    Route::prefix('admin')->as('admin.')->group(function () {
        Route::get('dashboard', function () {
            return view('admin.dashboard');
        })->name('dashboard');

        Route::get('settings/emails',   [\App\Http\Controllers\Admin\EmailsController::class, "create"])->name('settings.emails.create');
        Route::post('settings/emails',   [\App\Http\Controllers\Admin\EmailsController::class, "store"])->name('settings.emails.store');
        Route::resource('users', \App\Http\Controllers\Admin\UserController::class)->except(['show', 'destroy']);
        Route::resource('students', \App\Http\Controllers\Admin\StudentController::class)->except(['show', 'destroy']);
        Route::resource('instructors', \App\Http\Controllers\Admin\InstructorController::class)->except(['destroy']);
        Route::resource('instructor-levels', \App\Http\Controllers\Admin\InstructorLevelController::class);
        Route::resource('sub-instructors', \App\Http\Controllers\Admin\SubInstructorController::class)->except(['show', 'create', 'edit', 'update', 'store', 'destroy']);
        Route::resource('sessions', \App\Http\Controllers\Admin\SessionController::class)->except(['show', 'destroy']);
        Route::resource('packages', \App\Http\Controllers\Admin\PackageController::class)->except(['show', 'destroy']);
        Route::resource('plans', \App\Http\Controllers\Admin\PlanController::class)->except(['show', 'destroy']);
        Route::resource('terms', \App\Http\Controllers\Admin\TermController::class)->except(['show', 'destroy']);
        Route::resource('promocodes', \App\Http\Controllers\Admin\PromocodeController::class)->except(['update', 'store', 'show', 'destroy']);
        Route::resource('countries', \App\Http\Controllers\Admin\CountryController::class)->except(['create', 'edit', 'update', 'store', 'show', 'destroy']);
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', fn () => view('welcome'));
Route::get('/privacy-policy', fn () => view('privacy-policy'));
Route::get('/terms', fn () => view('terms'));

Route::prefix('storage')->group(fn () => [
    Route::get('image/{image_id}', 'storage@getImageFromModelFolder')->name('image_Real_path'),
    Route::get('file/{file_id}', 'storage@getFileFromModelFolder')->name('file_Real_path'),
    Route::get('video/{video_id}', 'storage@getVideoFromModelFolder')->name('video_Real_path'),
]);

Route::get('schedule', fn () => response()->json(['session' => App\Models\session::schedule(),  'instructor' => App\Models\instructor::schedule()]))->name('schedule');
Route::get('soka',function (){
    $details = [
        'email' => 'ahmed.salah.fcih@gmail.com',
        'type' => 'welcome_registration',
        'title' => 'Mail from quran academy',
        'body' => 'This is for testing email using smtp'
    ];



    dispatch(new App\Jobs\SendEventsEmailJob($details));

    dd("Email is Sent.");
});

app/Models/term.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class term extends Model
{
    protected $fillable = [
        'header',
        'body',
        'lang',
        'is_active',
        'is_visible',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'active_status_label',
        'active_status_color',
        'active_visible_label',
        'active_visible_color',
    ];

    // active status
    public const STATUS_ACTIVE = 1;
    public const STATUS_INACTIVE = 0;

    // visible status
    public const STATUS_VISIBLE = 1;
    public const STATUS_HIDDEN = 0;

    /**
     * active_status_label function
     *
     * @return string
     */
    public function getActiveStatusLabelAttribute()
    {
        return [
            self::STATUS_ACTIVE => 'Active',
            self::STATUS_INACTIVE => 'Inactive',
        ][$this->is_active] ?? 'Active';
    }

    /**
     * active_status_color function
     *
     * @return string
     */
    public function getActiveStatusColorAttribute()
    {
        return [
            self::STATUS_ACTIVE => 'green',
            self::STATUS_INACTIVE => 'red',
        ][$this->is_active] ?? 'green';
    }

    /**
     * active_visible_label function
     *
     * @return string
     */
    public function getActiveVisibleLabelAttribute()
    {
        return [
            self::STATUS_VISIBLE => 'Visible',
            self::STATUS_HIDDEN => 'Hidden',
        ][$this->is_visible] ?? 'Visible';
    }

    /**
     * active_visible_color function
     *
     * @return string
     */
    public function getActiveVisibleColorAttribute()
    {
        return [
            self::STATUS_VISIBLE => 'green',
            self::STATUS_HIDDEN => 'red',
        ][$this->is_visible] ?? 'green';
    }

    public function getPublic($root, $args)
    {
        return static::where('is_active', 1)->where('is_visible', 1)->where('lang', app()->getLocale())->get();
    }
}

app/Http/Controllers/Admin/TermController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\term;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Term\StoreTermRequest;
use App\Http\Requests\Admin\Term\UpdateTermRequest;

class TermController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.terms.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.terms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Admin\Term\StoreTermRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTermRequest $request)
    {

        $term = new term;
        $term->header = $request->header;
        $term->body = $request->body;
        $term->lang = $request->lang;
        $term->is_active = $request->is_active ? true : false;
        $term->is_visible = $request->is_visible ? true : false;
        $term->save();

        return redirect()->route('admin.terms.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  term $term
     * @return \Illuminate\Http\Response
     */
    public function edit(term $term)
    {
        return view('admin.terms.edit', compact('term'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Admin\Term\UpdateTermRequest  $request
     * @param  term $term
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTermRequest $request, term $term)
    {
        $term->header = $request->header;
        $term->body = $request->body;
        $term->lang = $request->lang;
        $term->is_active = $request->is_active ? true : false;
        $term->is_visible = $request->is_visible ? true : false;
        $term->update();

        return redirect()->route('admin.terms.index');
    }
}

app/Http/Livewire/Admin/Terms/Index.php
<?php

namespace App\Http\Livewire\Admin\Terms;

use App\Models\term;
use App\Http\Livewire\Admin\MainComponent;

class Index extends MainComponent
{

    protected $listeners = [
        'refreshImport' => '$refresh'
    ];

    public $filters = [
        'search' => null,
        'email' => null,
    ];

    public function getRowsQuery()
    {
        return term::query()
            ->when($this->filters['search'], fn ($query, $search) => $query->whereMacroSearch('header', strtolower($search)));
    }

    //TODO: find a cleaner way to handle this
    public function deleteSelected()
    {
        $deleteCount = $this->selectedRowsQuery->count();

        $this->selectedRowsQuery->get()->each(function ($user) {
            $user->delete();
        });

        $this->showDeleteModal = false;

        $this->macroNotify('You\'ve deleted ' . $deleteCount . ' terms');
    }

    public function render()
    {
        return view('livewire.admin.terms.index', [
            'rows' => $this->rows
        ])->layout('layouts.admin');
    }
}

resources/views/admin/terms/create.blade.php
<x-admin-layout>

    <x-slot name="title">{{__('Create Term And Condition')}}</x-slot>

    <form class="mt-4 space-y-4" method="POST" action="{{ route('admin.terms.store') }}" enctype="multipart/form-data">
        @csrf

        @include('admin.terms.field')

        <div class="flex items-center justify-end mt-4">
            <x-jet-button class="ml-4 btnColorBlueberry">
                {{ __('Create Term And Condition') }}
            </x-jet-button>
        </div>
    </form>

</x-admin-layout>

resources/views/admin/terms/edit.blade.php
<x-admin-layout>

    <x-slot name="title">{{__('Edit Term And Condition')}}: {{$term->header}}</x-slot>

    <form class="mt-4 space-y-4" method="POST" action="{{ route('admin.terms.update', $term->id) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        @include('admin.terms.field', [
            'term' => $term ?? null
        ])

        <div class="flex items-center justify-end mt-4">
            <x-jet-button class="ml-4 btnColorBlueberry">
                {{ __('Update Term And Condition') }}
            </x-jet-button>
        </div>
    </form>

</x-admin-layout>

resources/views/admin/terms/field.blade.php
<div>
    <x-jet-label for="header" value="{{ __('Header') }}" />
    <x-input.textarea
        id="header"
        name="header"
        value='{!! old("header", $term->header ?? null) !!}'
        >
    </x-input.textarea>
    <x-jet-input-error for="header" class="mt-2" />
</div>

<div>
    <x-jet-label for="body" value="{{ __('Body') }}" />
    <x-input.textarea
        id="body"
        name="body"
        value='{!! old("body", $term->body ?? null) !!}'
        >
    </x-input.textarea>
    <x-jet-input-error for="body" class="mt-2" />
</div>

<div class="mt-4">
    <x-jet-label for="lang" value="{{ __('Language') }}" />
    <x-input.select id="lang" name="lang">
        <option value="en" {{ $term != null && $term->lang == 'en' ? 'selected' : '' }}>{{__('English')}}</option>
        <option value="ar" {{ $term != null && $term->lang == 'ar' ? 'selected' : '' }}>{{__('Arabic')}}</option>
    </x-input.select>
    <x-jet-input-error for="lang" class="mt-2" />
</div>

<div>
    <x-jet-label for="is_active" value="Active Status" />
    <div class="flex rounded-md">
        <input id="is_active"
            name="is_active"
            value="on"
            {{ old('is_active') == 'on' ? 'checked' : '' }}
            {{ ($term && $term->is_active == true) ? 'checked' : '' }}
            type="checkbox"
            class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded"
        />
    </div>
    <x-jet-input-error for="is_active" class="mt-2" />
</div>

<div>
    <x-jet-label for="is_visible" value="Visible Status" />
    <div class="flex rounded-md">
        <input id="is_visible"
            name="is_visible"
            value="on"
            {{ old('is_visible') == 'on' ? 'checked' : '' }}
            {{ ($term && $term->is_visible == true) ? 'checked' : '' }}
            type="checkbox"
            class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded"
        />
    </div>
    <x-jet-input-error for="is_visible" class="mt-2" />
</div>

resources/views/admin/terms/index.blade.php
<x-admin-layout>
    <x-slot name="title">
        <h2 class="text-xl">
            {{__('Terms And Conditions')}}
        </h2>
    </x-slot>

    <livewire:admin.terms.index />
</x-admin-layout>