routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware(['auth:sanctum', 'verified'])->group(function () {

    Route::prefix('admin')->as('admin.')->group(function () {
        Route::get('dashboard', function () {
            return view('admin.dashboard');
        })->name('dashboard');

        Route::get('settings/emails',   [\App\Http\Controllers\Admin\EmailsController::class, "create"])->name('settings.emails.create');
        Route::post('settings/emails',   [\App\Http\Controllers\Admin\EmailsController::class, "store"])->name('settings.emails.store');
        Route::resource('users', \App\Http\Controllers\Admin\UserController::class)->except(['show', 'destroy']);
        Route::resource('students', \App\Http\Controllers\Admin\StudentController::class)->except(['show', 'destroy']);
        Route::resource('instructors', \App\Http\Controllers\Admin\InstructorController::class)->except(['destroy']);
        Route::resource('instructor-levels', \App\Http\Controllers\Admin\InstructorLevelController::class);
        Route::resource('sub-instructors', \App\Http\Controllers\Admin\SubInstructorController::class)->except(['show', 'create', 'edit', 'update', 'store', 'destroy']);
        Route::resource('sessions', \App\Http\Controllers\Admin\SessionController::class)->except(['show', 'destroy']);
        Route::resource('packages', \App\Http\Controllers\Admin\PackageController::class)->except(['show', 'destroy']);
        Route::resource('plans', \App\Http\Controllers\Admin\PlanController::class)->except(['show', 'destroy']);
        Route::resource('terms', \App\Http\Controllers\Admin\TermController::class)->except(['show', 'destroy']);
        Route::resource('promocodes', \App\Http\Controllers\Admin\PromocodeController::class)->except(['update', 'store', 'show', 'destroy']);
        Route::resource('countries', \App\Http\Controllers\Admin\CountryController::class)->except(['create', 'edit', 'update', 'store', 'show', 'destroy']);
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', fn () => view('welcome'));
Route::get('/privacy-policy', fn () => view('privacy-policy'));
Route::get('/terms', fn () => view('terms'));

Route::prefix('storage')->group(fn () => [
    Route::get('image/{image_id}', 'storage@getImageFromModelFolder')->name('image_Real_path'),
    Route::get('file/{file_id}', 'storage@getFileFromModelFolder')->name('file_Real_path'),
    Route::get('video/{video_id}', 'storage@getVideoFromModelFolder')->name('video_Real_path'),
]);

Route::get('schedule', fn () => response()->json(['session' => App\Models\session::schedule(),  'instructor' => App\Models\instructor::schedule()]))->name('schedule');
Route::get('soka',function (){
    $details = [
        'email' => 'ahmed.salah.fcih@gmail.com',
        'type' => 'welcome_registration',
        'title' => 'Mail from quran academy',
        'body' => 'This is for testing email using smtp'
    ];



    dispatch(new App\Jobs\SendEventsEmailJob($details));

    dd("Email is Sent.");
});

app/Models/InstructorLevel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class InstructorLevel extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = [];

    public static function boot()
    {
        parent::boot();
        static::deleting(function ($level) {
            $instructors = instructor::where('instructor_level_id', $level->id)->get();
            foreach ($instructors as $instructor) {
                $instructor->instructor_level_id = null;
                $instructor->save();
            }

            $plans = Plan::where('instructor_level_id', $level->id)->get();
            foreach ($plans as $plan) {
                $plan->instructor_level_id = null;
                $plan->save();
            }
        });

    }


    public function instructors()
    {
        return $this->hasMany(instructor::class,'instructor_level_id','id');
    }

}

app/Http/Controllers/Admin/InstructorLevelController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\InstructorLevel\StoreInstructorLevelRequest;
use App\Http\Requests\Admin\InstructorLevel\UpdateInstructorLevelRequest;
use App\Http\Requests\Admin\Package\StorePackageRequest;
use App\Http\Requests\Admin\Package\UpdatePackageRequest;
use App\Models\InstructorLevel;
use App\Models\Package;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class InstructorLevelController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth']);
    }

    public function index()
    {
        return view('admin.instractor_levels.index');
    }

    public function create()
    {
        return view('admin.instractor_levels.create');
    }

    public function store(StoreInstructorLevelRequest $request)
    {
        $instructor_level = new InstructorLevel();
        $instructor_level->name = $request->name;
        $instructor_level->save();
        return redirect()->route('admin.instructor-levels.index');
    }

    public function edit(InstructorLevel $instructorLevel)
    {
        return view('admin.instractor_levels.edit')->with([
            'level' => $instructorLevel,
        ]);
    }

    public function update(UpdateInstructorLevelRequest $request, InstructorLevel $instructorLevel)
    {
        $instructorLevel->name = $request->name;
        $instructorLevel->update();
        return redirect()->route('admin.instructor-levels.index');
    }

    public function destroy(InstructorLevel $instructorLevel)
    {
        $instructorLevel->delete();
        return redirect()->route('admin.instructor-levels.index');
    }
}

app/Http/Livewire/Admin/InstructorLevels/Index.php
<?php

namespace App\Http\Livewire\Admin\InstructorLevels;

use App\Http\Livewire\Admin\MainComponent;
use App\Models\InstructorLevel;
use Livewire\Component;

class Index extends MainComponent
{
    public function mount()
    {
    }

    public function getRowsQuery()
    {
        return InstructorLevel::query();
    }

    public function render()
    {
        return view('livewire.admin.instructor-levels.index', [
            'rows' => $this->rows
        ])->layout('layouts.admin');
    }
}

resources/views/livewire/admin/instructor-levels/index.blade.php
<div>
    <div class="py-5 space-y-5">
        <div class="flex justify-between">
            <div class="flex w-2/4 space-x-4"></div>

            <div class="flex items-center space-x-2">
                <x-link.primary href="{{ route('admin.instructor-levels.create') }}" class="bg-green-600 hover:bg-green-500 active:bg-green-700 border-green-600"><x-icon.plus/>
                       {{ __('New') }}
                </x-link.primary>
            </div>
        </div>
        <div class="flex-col space-y-4">

            <x-table>
                <x-slot name="head">
                    <x-table.heading sortable multi-column wire:click="sortBy('name')" :direction="$sorts['name'] ?? null">{{ __('Name') }}</x-table.heading>
                    <x-table.heading sortable multi-column >{{ __('Action') }}</x-table.heading>
                </x-slot>

                <x-slot name="body">


                    @forelse ($rows as $row)
                        <x-table.row wire:loading.class.delay="opacity-50" wire:key="row-{{ $row->id }}">
                            <x-table.cell><span>{{$row->name}}</span></x-table.cell>

                                <x-table.cell>
                                <x-link.secondary href="{{route('admin.instructor-levels.edit',$row->id)}}" >{{ __('Edit') }}</x-link.secondary>

                                    <form style="display: inline" action="{{route('admin.instructor-levels.destroy',$row->id)}}" method="post">
                                        @csrf
                                        {{method_field('DELETE')}}
                                        <x-button.red type="submit" class="btn btn-danger"> {{__('Delete')}}</x-button.red>
                                    </form>
                            </x-table.cell>
                        </x-table.row>
                    @empty
                        <x-table.row>
                            <x-table.cell colspan="7">
                                <div class="flex items-center justify-center space-x-2">
                                    <x-icon.no-record class="w-8 h-8 text-cool-gray-400" />
                                    <span class="py-8 text-xl font-medium text-cool-gray-400">{{ __('No record found') }}</span>
                                </div>
                            </x-table.cell>
                        </x-table.row>
                    @endforelse
                </x-slot>
            </x-table>

            <div>
                {{ $rows->links() }}
            </div>
        </div>
    </div>
</div>